Update Readme
KIT-IAI/pyWATTS pull request #186
Opened 2022-03-03 13:00 UTC by kalebphipps

Two small changes:
- Fixed names in the citation so they are all written the same (first name last name).
- Added an E-Mail address for contact purposes.

## Description

## Related Issues

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos)
- [X] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [X] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [X] Did you verify new and existing tests pass locally with your changes?
- [] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] Did you update the CHANGELOG

## PR review
Anyone in the community is free to review the PR once the tests have passed.

- [X ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones to the PR so it can be classified

2022-03-03 16:04 UTC, marianturowski requested changes
Please also adapt the funding: Update Helmholtz AI and add Energy System Design:

"Helmholtz Association’s Initiative and Networking Fund through Helmholtz AI" 
"the Helmholtz Association under the Program “Energy System Design”

2022-03-04 09:11 UTC, marianturowski approved these changes
That's fine. Thank you!

2022-03-04 10:55 UTC, kalebphipps commented
"the"  added :)

2022-03-04 12:39 UTC, marianturowski approved these changes

2022-03-07 16:30 UTC, merged