Update about_us
KIT-IAI/pyWATTS pull request #187
Opened 2022-03-03 14:09 UTC by kalebphipps

Two small changes:
- Added Stefan.
- Added the link to the paper.

## Description

## Related Issues

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos)
- [X] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] Did you update the CHANGELOG

## PR review
Anyone in the community is free to review the PR once the tests have passed.

- [X] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [X] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones to the PR so it can be classified

2022-03-03 16:21 UTC, kalebphipps commented
Funding should now be ok (I hope)

2022-03-04 09:12 UTC, marianturowski commented on docs/source/about_us.rst
> +This project is supported by the Helmholtz Association under the Program “Energy System Design”, by Helmholtz Association’s Initiative and Networking Fund through Helmholtz AI, by the Helmholtz Assoc
..., by the Helmholtz...

2022-03-04 09:17 UTC, marianturowski requested changes
Please add a "the" in line 42

2022-03-04 10:55 UTC, kalebphipps commented
"the"  added :)

2022-03-04 12:40 UTC, marianturowski approved these changes

2022-03-07 16:31 UTC, merged