Feature/228 more flexible pnn
KIT-IAI/pyWATTS pull request #231
Opened 2022-05-20 11:20 UTC by benHeid

## Description

## Related Issues
closes #228 
## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos)
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Did you update the CHANGELOG

## PR review
Anyone in the community is free to review the PR once the tests have passed.

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones to the PR so it can be classified

2022-05-20 14:59 UTC, marianturowski requested changes
Thank you for making the PNN more flexible.
Please consider adapting the comments in the code as I suggested.

2022-05-20 14:59 UTC, marianturowski commented on pywatts/modules/models/profile_neural_network.py
Do you want to leave the list of the inputs (in lines 84 to 95) as it is or do you want to change it kwargs accordingly?

2022-05-20 14:59 UTC, marianturowski commented on pywatts/modules/models/profile_neural_network.py
Lines 114 to 125: see above? Adapt it to kwargs?

2022-05-23 07:51 UTC, benHeid commented on pywatts/modules/models/profile_neural_network.py
> +    def _get_inputs(self, kwargs, offset):
I added a comment

2022-05-23 08:03 UTC, marianturowski commented on pywatts/modules/models/profile_neural_network.py
I see your point. That's fine.

2022-05-23 08:04 UTC, marianturowski commented on pywatts/modules/models/profile_neural_network.py
I see your point. That's fine.

2022-05-23 08:06 UTC, marianturowski requested changes
I suggest two small changes in new comments

2022-05-23 08:06 UTC, marianturowski commented on pywatts/modules/models/profile_neural_network.py
> +        Forecast the electrical load for the given input. Note historical_input, trend, and profile has to be provided.
Please change:
Forecast the electrical load for the given input. Note that historical_input, trend, and profile have to be provided.

2022-05-23 08:06 UTC, marianturowski commented on pywatts/modules/models/profile_neural_network.py
> +        Fit the Profile Neural Network. Note historical_input, trend, and profile has to be provided.
Fit the Profile Neural Network. Note that historical_input, trend, and profile have to be provided.

2022-05-23 10:58 UTC, merged